

# This file was *autogenerated* from the file ex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_31 = Integer(31); _sage_const_1 = Integer(1); _sage_const_197670581 = Integer(197670581); _sage_const_917995853 = Integer(917995853); _sage_const_1371741767 = Integer(1371741767); _sage_const_406819140 = Integer(406819140); _sage_const_1281752765 = Integer(1281752765); _sage_const_1564335693 = Integer(1564335693); _sage_const_711495991 = Integer(711495991); _sage_const_1476685420 = Integer(1476685420); _sage_const_1717841229 = Integer(1717841229); _sage_const_1996471878 = Integer(1996471878); _sage_const_1827963874 = Integer(1827963874); _sage_const_1588780450 = Integer(1588780450); _sage_const_625001828 = Integer(625001828); _sage_const_119159153 = Integer(119159153); _sage_const_240333459 = Integer(240333459); _sage_const_848697795 = Integer(848697795); _sage_const_1138767216 = Integer(1138767216); _sage_const_39349376 = Integer(39349376); _sage_const_2047427983 = Integer(2047427983); _sage_const_874150208 = Integer(874150208)
p = _sage_const_2 **_sage_const_31  - _sage_const_1 
Fp = GF(p)

# i^2 = -1
R = PolynomialRing(Fp, names=('X',)); (X,) = R._first_ngens(1)
CM31 = Fp.extension(X**_sage_const_2  + _sage_const_1 , names=('i',)); (i,) = CM31._first_ngens(1)

# u^2 = 2 + i
S = PolynomialRing(CM31, names=('Y',)); (Y,) = S._first_ngens(1)
QM31 = CM31.extension(Y**_sage_const_2  - (CM31(_sage_const_2 ) + i), names=('u',)); (u,) = QM31._first_ngens(1)

# element format: (a + b*i) + (c + d*i)*u
def qm31(a,b,c,d):
    return CM31(a) + CM31(b)*i + (CM31(c) + CM31(d)*i)*u


tar = (_sage_const_197670581  + _sage_const_917995853 *i) + (_sage_const_1371741767  + _sage_const_406819140 *i)*u
a = (_sage_const_1281752765  + _sage_const_1564335693 *i) + (_sage_const_711495991  + _sage_const_1476685420 *i)*u

b = (_sage_const_1717841229  + _sage_const_1996471878 *i) + (_sage_const_1827963874  + _sage_const_1588780450 *i)*u

d = b - a

ans = (tar - a) / d

print(ans)
exit()

# examples (your two values)
x = qm31(_sage_const_625001828 , _sage_const_119159153 , _sage_const_240333459 , _sage_const_848697795 )
y = qm31(_sage_const_1138767216 , _sage_const_39349376 , _sage_const_2047427983 , _sage_const_874150208 )

print("x =", x)
print("y =", y)
print("x+y =", x + y)
print("x*y =", x * y)
print("x^-1 =", x**-_sage_const_1 )

